// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAvvbhAIS7JsYZACDDEOTW5d8SCabnFeM',
    appId: '1:112024232890:web:743abbcf8564368c3b7383',
    messagingSenderId: '112024232890',
    projectId: 'text-me-835c4',
    authDomain: 'text-me-835c4.firebaseapp.com',
    storageBucket: 'text-me-835c4.firebasestorage.app',
    measurementId: 'G-23WY5K2191',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIIXZSli8lWjxisDqkVSnI8vLt0GP0To',
    appId: '1:112024232890:android:7cc302fb618196503b7383',
    messagingSenderId: '112024232890',
    projectId: 'text-me-835c4',
    storageBucket: 'text-me-835c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvJaO-dtS9YyMdDSszXR1Co1IOyKEuigA',
    appId: '1:112024232890:ios:f5be5400874ff1213b7383',
    messagingSenderId: '112024232890',
    projectId: 'text-me-835c4',
    storageBucket: 'text-me-835c4.firebasestorage.app',
    iosBundleId: 'com.example.textMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvJaO-dtS9YyMdDSszXR1Co1IOyKEuigA',
    appId: '1:112024232890:ios:f5be5400874ff1213b7383',
    messagingSenderId: '112024232890',
    projectId: 'text-me-835c4',
    storageBucket: 'text-me-835c4.firebasestorage.app',
    iosBundleId: 'com.example.textMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAvvbhAIS7JsYZACDDEOTW5d8SCabnFeM',
    appId: '1:112024232890:web:0ca8615a6c4155e53b7383',
    messagingSenderId: '112024232890',
    projectId: 'text-me-835c4',
    authDomain: 'text-me-835c4.firebaseapp.com',
    storageBucket: 'text-me-835c4.firebasestorage.app',
    measurementId: 'G-W6EK42Z0V4',
  );
}
